server {
    listen 80;

    location /events {
        proxy_pass http://host.docker.internal:8010;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
    }

    location /terminal/ {
        proxy_pass http://host.docker.internal:8010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }

    location /api/ {
        proxy_pass http://host.docker.internal:8010;
    }

    location / {
        proxy_pass http://host.docker.internal:8010;
    }
}
